name: chatbot-rag-backend
services:
  - name: backend
    git:
      repository: github.com/BartClo/ProyectoIngSoftware
      branch: main
      workdir: /backend
    instance_type: nano
    ports:
      - port: 8000
        protocol: http
    environment:
      - key: GROQ_API_KEY
        value: SECRET
      - key: PINECONE_API_KEY  
        value: SECRET
      - key: PINECONE_ENVIRONMENT
        value: gcp-starter
      - key: PINECONE_INDEX_NAME
        value: chatbot-rag-index
      - key: SECRET_KEY
        value: SECRET
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: SECRET
    health_check:
      http:
        port: 8000
        path: /health
    build:
      buildpack: python
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT