version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ia
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatbot

  ia:
    build: ./ia
    volumes:
      - ./ia:/app
    environment:
      - MODEL_PATH=/models/gpt4all

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB=chatbot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
