services:
  - name: chatbot-rag-backend
    source:
      repo: BartClo/ProyectoIngSoftware
      rootDirectory: /backend
    build:
      buildCommand: pip install -r requirements.txt
    deploy:
      startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
      healthcheckPath: /health
      healthcheckTimeout: 300
    variables:
      GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
      PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY}}
      PINECONE_ENVIRONMENT: gcp-starter
      PINECONE_INDEX_NAME: chatbot-rag-index
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      DATABASE_URL: ${{Postgres.DATABASE_URL}}
      ENVIRONMENT: production
  
  - name: chatbot-rag-db
    type: postgresql